# Generated by Django 5.0.2 on 2024-03-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='id_stripe_session',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id сессии stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_succeed',
            field=models.BooleanField(default=False, verbose_name='оплата завершена'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'наличные'), ('card', 'оплата картой')], default='card', max_length=20, verbose_name='способ оплаты'),
        ),
    ]
