# Generated by Django 5.0.2 on 2024-03-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment_id_stripe_session_payment_is_succeed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_payment',
            field=models.DateField(auto_now_add=True, verbose_name='дата платежа'),
        ),
    ]
