# Generated by Django 5.0.2 on 2024-03-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_payment_payment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='ссылка на оплату'),
        ),
    ]
