# Generated by Django 5.0.2 on 2024-03-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_course_last_update_course_price_course_stripe_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id цены в stripe'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id цены в stripe'),
        ),
    ]
